image_analyzer:
  fields:
    provider:
      description: 'Select Provider'
      required: true
      default: 'OpenAI'
      selector:
        select:
          options:
            - 'OpenAI'
            - 'LocalAI'
    message:
      required: true
      description: 'Prompt'
      example: "Describe the person present in the photo"
      selector:
        text:
          multiline: true
    max_tokens:
      required: true
      example: 100
      default: 100
      selector:
        number:
          min: 10
          max: 1000
    image_file:
      required: true
      description: 'The path to you image'
      example: "/config/www/images/img.jpg"
      selector:
        text:
          multiline: true
    model:
      required: false
      description: 'Which model to use'
      example: "gpt-4o"
      default: "gpt-4o"
      selector:
        text:
          multiline: false
    target_width:
      required: false
      description: 'Width (in px) to downscale to'
      example: 1280
      default: 1280
      selector:
        number:
          min: 640
          max: 3840