blueprint:
  name: Camera Motion Summary (LLM Vision v1.2.1)
  author: valentinfrlch
  description: Summarizes camera motion events and sends a notification to your phone
  domain: automation
  input:
    notify_device:
      name: Notify Device
      description: The device to send the notification to
      selector:
        device:
          integration: mobile_app
    camera_entities:
      name: Camera Entities
      description: List of camera entities to monitor
      selector:
        entity:
          domain: camera
          multiple: true
    trigger_state:
      name: Trigger State
      description: The state the camera has to be in to trigger the automation
      default: recording
      selector:
        text:
          multiline: false
    tap_navigate:
      name: Tap Navigate
      description: Relativ path to navigate to when pressing notification (e.g. /lovelace/cameras)
      selector:
        text:
          multiline: false
    cooldown:
      name: Cooldown
      description: Time in minutes to wait before running again
      default: 10
      selector:
        number:
          min: 0
          max: 60
    provider:
      name: Provider
      description: Configuration to use for the video_analyzer service. See docs for additional information.
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      description: Model to use for the video_analyzer service
      default: "gpt-4o-mini"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      description: Model prompt for the video_analyzer service
      default: "Summarize briefly what's happening in the camera feed (one sentence max). Don't describe the scene! If there is a person, describe what they're doing. If nothing is happening, say so."
      selector:
        text:
          multiline: true
    duration:
      name: Duration
      description: How long to record for (in seconds)
      default: 5
      selector:
        number:
          min: 1
          max: 60    
    interval:
      name: Interval
      description: Analyze frames every <interval> seconds
      default: 3
      selector:
        number:
          min: 1
          max: 60
    max_frames:
      name: Max Frames
      description: How many frames to analyze. Picks frames with the most movement.
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1
    target_width:
      name: Target Width
      description: Width in pixels to downscale (uses less tokens)
      default: 1280
      selector:
        number:
          min: 512
          max: 1920
    detail:
      name: Detail
      description: Detail parameter (OpenAI only)
      default: 'low'
      selector:
        select:
          options:
            - 'high'
            - 'low'
    max_tokens:
      name: Maximum Tokens
      description: Maximum number of tokens to generate
      default: 50
      selector:
        number:
          min: 1
          max: 100
    temperature:
      name: Temperature
      description: Randomness. Lower is more accurate, higher is more creative
      default: 0.1
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1

variables:
  cooldown: !input cooldown
  label: "{{ trigger.payload_json.after.label|capitalize }}"
  camera: '{{ trigger.entity_id.replace("camera.", "").replace("_", " ")|capitalize }}'
  video_preview: "{{base_url}}/api/events/{{trigger.payload_json['after']['id']}}/clip.mp4"
  image_preview: "{{base_url}}/api/events/{{trigger.payload_json['after']['id']}}/snapshot.jpg"
  tag: "{{trigger.entity_id + int(as_timestamp(now()))|string}}"
  group: "{{trigger.entity_id}}"

mode: single
trigger:
  platform: state
  entity_id: !input camera_entities
  to: !input trigger_state

condition:
  - condition: template
    value_template: >
      {{ state_attr(this.entity_id, 'last_triggered') is none or 
         (now() - state_attr(this.entity_id, 'last_triggered')).total_seconds() / 60 > cooldown }}

action:
  - alias: "Send instant notification without summary"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    title:  "Motion detected"
    message: '{{camera}}'
    data:
      image: "{{'/api/camera_proxy/' + trigger.entity_id}}"
      tag: "{{tag}}"
      group: "{{group}}"
    

  - alias: "Analyze camera stream"
    service: llmvision.stream_analyzer
    data:
      provider: !input provider
      model: !input model
      message: !input message
      image_entity: !input camera_entities
      max_frames: !input max_frames
      duration: !input duration
      include_filename: true
      target_width: !input target_width
      detail: !input detail
      max_tokens: !input max_tokens
      temperature: !input temperature
    response_variable: response

  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: '{{ trigger.entity_id.replace("camera.", "").replace("_", " ")|capitalize }}'
    message: "{{ response.response_text }}"
    data:
      tag: "{{tag}}"
      group: "{{group}}"
      image: "{{'/api/camera_proxy/' + trigger.entity_id}}"
      url: !input tap_navigate #iOS
      clickAction: !input tap_navigate #Android
      push:
        interruption-level: passive